### ISSUE TITLE
ModuleNotFoundError: No module named 'kivymd.uix.relativelayout'

### ISSUE THREAD

**Issue by prawnydagrate** [kivymd-extensions/filemanager#3]
### Description of the Bug
I was installing and trying out these KivyMD extensions. All of them worked fine, but when I tried to run the File Manager I got an error.

### Code and Logs

```python
from kivymd.app import MDApp

from kivymd_extensions.filemanager import FileManager


class MainApp(MDApp):
    def on_start(self):
        FileManager().open()


if __name__ == "__main__":
    MainApp().run()
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Versions

* OS: Manjaro Linux
* Python: 3.8.6
* Kivy: 1.11.1
* KivyMD: 0.104.1

**Comment by HeaTTheatR** [comment]
@Python3-8 Update KivyMD library from master branch.
