### ISSUE TITLE
The examples crash after runnning the code - There is no Error just a warning message.

### ISSUE THREAD

**Issue by romybompart** [kivymd-extensions/filemanager#4]
### Description of the Bug

After running the example the application windows attempts to launch the filemanager, nevertheless it closed itself.  I can't use the example to evaluate the code. 

### Code and Logs

[INFO   ] [Logger      ] Record log in C:\Users\Romy1\.kivy\logs\kivy_21-01-22_48.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "c:\Users\Romy1\Anaconda3\envs\kivy_env\python.exe"
[INFO   ] [KivyMD      ] 0.104.2.dev0, git-Unknown, 2021-01-23 (installed at "c:\Users\Romy1\Anaconda3\envs\kivy_env\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 24.20.100.6286'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 620'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 24.20.100.6286'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] [Factory     ] Ignored class "FileListEntry" re-declaration. Current -  module: None, cls: functools.partial(<bound method BuilderBase.template of <kivy.lang.builder.BuilderBase object at 0x00000203FDD42788>>, 'FileListEntry'), baseclass: None, filename: None. Ignored -  module: None, cls: functools.partial(<bound method BuilderBase.template of <kivy.lang.builder.BuilderBase object at 0x00000203FDD42788>>, 'FileListEntry'), baseclass: None, filename: None.
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[Finished in 3.5s]

### Versions

* OS:  Windows 10
* Python: 3.7.7
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0

**Comment by maleksware** [comment]
Please attach the code that produces the bug.

**Comment by HeaTTheatR** [comment]
Fixed in last commits.
